name: snakeit # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Snake just like on the old NOKIA phones! # 79 char long summary
description: |
  A simple text-bases implementation of the class Snake game.
  Collect food to make your snake longer and try to not hit
  any walls or your tail!

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  snakeit:
    command: bin/snakeit

parts:
  snakeit:
    source: https://github.com/IsakTheHacker/snakeit.git
    source-type: git
    override-pull: snapcraftctl pull && mkdir bin
    plugin: make
    build-packages: [libncurses-dev]
