name: Makefile CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare build
      run: mkdir bin
    
    - name: Build project
      run: make
