name: Snapcraft Build & Publish

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build project!
      uses: snapcore/action-build@v1
      id: build
    
    - name: Publish to the snapstore
      uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: stable
